tests/common/snappi_tests/snappi_fixtures.py

Summary: Removing unused fixtures: get_multidut_tgen_peer_port_set and get_multidut_snappi_ports from snappi_fixtures.py Fixes # (issue) #16015
deleted the code

[#16015 Fix]: Cleaning up unused code from snappi_fixtures (#16026)

---

tests/common/devices/multi_asic.py
tests/common/platform/interface_utils.py
tests/common/platform/transceiver_utils.py
tests/common/port_toggle.py
tests/platform_tests/api/test_sfp.py
tests/platform_tests/sfp/test_sfputil.py

Merge #16547 #16375 into msft 202405 branch

Merge #16547 #16375 into msft 202405 branch

---

tests/acl/test_acl.py
tests/common/reboot.py

Merge github 202405 branch

---

tests/conftest.py

Summary: fix conflict for https://github.com/sonic-net/sonic-mgmt/pull/16626
Summary:
Fixes # (issue) 30545289
Add console_password as the password for console login as some devices might use this during setup.
Add console_password as the password for console login as some devices might use this during setup.
-->

fix conflict #16626

---

tests/test_nbr_health.py

We consider the script test_nbr_health.py as applicable to all topologies. In this PR, we update the topology mark for the script to enable it to run on all topologies
Update the topology mark for script test_nbr_health.py to enable it to run on all topologies
Summary:

feat: support nbr health test on T2 chassis

---

tests/macsec/test_deployment.py

Add new scale test test_scale_rekey : https://github.com/sonic-net/sonic-mgmt/pull/14502
Summary:

[MACSEC] Cherry pick PR 14502

---

.github/workflows/autosync_pub_msft.yml

Since the GitHub Action token lacks the necessary permissions to create a PR and modifying its privileges is challenging, we have decided to push the code directly to the target branch instead of creating a PR.
Summary:
Since the GitHub Action token lacks the necessary permissions to create a PR and modifying its privileges is challenging, we have decided to push the code directly to the target branch instead of creating a PR.
Push the code directly to the target branch instead of creating a PR.
For reference: https://github.com/yutongzhang-microsoft/sonic-mgmt/actions/runs/13512702017

[Auto Sync] Push code directly to target branch.

---

.github/workflows/autosync_pub_msft.yml

Since the 202412 branch does not exist in the public sonic-mgmt repository, the auto-sync process encounters the error:
`fatal: ambiguous argument 'head/202412': unknown revision or path not in the working tree.` This PR resolves the issue by updating the target branch to 202411.
Summary:
Since the 202412 branch does not exist in the public sonic-mgmt repository, the auto-sync process encounters the error:
`fatal: ambiguous argument 'head/202412': unknown revision or path not in the working tree.` This PR resolves the issue by updating the target branch to 202411.
This PR resolves the issue by updating the target branch to 202411.

[Auto Sync] Fix auto-sync error by updating target branch to 202411

---

ansible/library/vlan_config.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

This PR is for fixing the bad conflict resolve result from the automation in this commit: https://github.com/Azure/sonic-mgmt.msft/commit/cdd423dfa8cd4f4e0f8c946d95c6a654725689fe.
For example:

Fix bad merge result from automation.

---

tests/generic_config_updater/test_dynamic_acl.py

Fix merge conflict caused by commit 847fb81
Summary:
Fix merge conflict caused by commit 847fb81

Fix merge conflict caused by commit 847fb81

---

.github/workflows/autosync_pub_msft.yml

Handle code conflict.

---

.github/workflows/autosync_pub_msft.yml

We have an automatic sync workflow. Previously, it was triggered manually. In this PR, we update it to run automatically every day at 00:00 UTC.
Summary:
We have an automatic sync workflow. Previously, it was triggered manually. In this PR, we update it to run automatically every day at 00:00 UTC.

Enable daily auto sync workflow.

---

tests/common/plugins/sanity_check/__init__.py

Optimize the `print_logs()` method in `plugins/sanity_check/__init__.py` by Python multithreading.
Summary:
Fixes # (issue) Microsoft ADO 30849826
We wanted to reduce the preparation time for multi-DUT devices (e.g. T2 devices) by optimizing the `print_logs()` method in `plugins/sanity_check/__init__.py`.
I ran the updated code and can make sure it's working well.

[manual] [PR:17423] refactor: optimize print logs by multithreading

---

tests/common/helpers/dut_utils.py
tests/show_techsupport/test_auto_techsupport.py
tests/srv6/conftest.py
tests/srv6/srv6_utils.py
tests/srv6/test_srv6_dataplane.py

Test coverage:
1.Cover DIP shift function
2.Cover uSID container copy and segment left reduce function
3.Cover USD function including pipe mode
4.Cover Config reload / cold reboot
5.Cover SAI SDK dump validation
After synced with Changrong Wu, we agreed to merge this script into the tests/srv6/test_srv6_dataplane.py
Summary:
Implement the data plane test script for SRv6 function
Implement the data plane test script for SRv6 function and merge with the tests/srv6/test_srv6_dataplane.py.
Run it in local setup

Add SRv6 data plane test script

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Code sync sonic-net/sonic-mgmt:202411 => 202412

[202412] Code sync sonic-net/sonic-mgmt:202411 => 202412

---

tests/everflow/everflow_test_utilities.py

Summary:
This is a **cherry-pick PR** for https://github.com/sonic-net/sonic-mgmt/pull/17836
- Split the original PR https://github.com/sonic-net/sonic-mgmt/pull/17130 into individual PRs for each test.
- This is an enhancement to support VOQ Single DUT Multi-ASIC setup for T2 topo.
- New testbed modification of VOQ Single DUT and multi-asic.
- If T2 topo, decide based on the number of Duts.
- T2 VOQ Single Dut Multi ASIC

[Cherry-Pick PR#17836] - Everflow - Changes for VOQ single-dut multi-asic

---

.github/workflows/branch_sync.yml

Sync msft 202412 to msft 202503 branch
Summary:
For test, refer to https://github.com/yutongzhang-microsoft/sonic-mgmt/actions/runs/14565246169/job/40853553502

Sync from 202412 branch to 202503 branch.

---

.github/workflows/automerge_scan.yml
.github/workflows/autosync_msft_msft.yml
.github/workflows/autosync_pub_msft.yml
.github/workflows/codeql-analysis.yml
.github/workflows/pr_cherrypick_poststep.yml
.github/workflows/pr_cherrypick_prestep.yml
.github/workflows/semgrep.yml

Migrate github action workflows to main branch.

Migrate github action workflows to main branch.

---

ansible/library/generate_golden_config_db.py

Cherry-picked from https://github.com/sonic-net/sonic-mgmt/pull/18360

Support generating golden_config for topo ft2-64

---

ansible/library/announce_routes.py

Cherry-pick PR https://github.com/sonic-net/sonic-mgmt/pull/18325

Support announcing routes from LT2 to FT2

---

tests/common/helpers/voq_helpers.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/voq/test_voq_chassis_app_db_consistency.py
tests/voq/test_voq_disrupts.py
tests/voq/test_voq_fabric_capacity.py
tests/voq/test_voq_ipfwd.py

Cherry pick of https://github.com/sonic-net/sonic-mgmt/pull/18062
Depends on https://github.com/Azure/sonic-mgmt.msft/pull/252
We should first merge https://github.com/Azure/sonic-mgmt.msft/pull/252, this will cause a conflict which I can resolve with a rebase and then we should merge this in.

[msft-202503] Cherry pick PR18062: Voq tests changes to support single-dut-multi-asic

---

tests/common/helpers/dut_utils.py

Cherry-pick the fix of `verify_orchagent_running_or_assert` in following PRs to msft-202503:
- https://github.com/sonic-net/sonic-mgmt/pull/16065
- https://github.com/sonic-net/sonic-mgmt/pull/18463

[msft-202503] Fix verify_orchagent_running_or_assert for multi-ASIC

---

tests/common/snappi_tests/snappi_fixtures.py
tests/common/snappi_tests/traffic_generation.py
tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
tests/snappi_tests/pfcwd/files/pfcwd_burst_storm_helper.py
tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py

Update snappi_fixtures.py
updated to incorporate new snappi build changes
Update traffic_generation.py
updated new snappi build changes
Update traffic_generation.py
updated capture code
Update pfcwd_multi_node_helper.py
updated to support new snappi model
Update pfcwd_runtime_traffic_helper.py
updated file to accommodate new snappi changes.
Update pfcwd_burst_storm_helper.py
updated file to accommodate new snappi changes
Update pfcwd_basic_helper.py
updating files to accommodate snappi changes
Approach
To support new snappi model changes
Snappi-fixtures.py file is modified to accommodate port connections. traffic-generation.py file accommodates traffic start/stop and capture start/stop operations. Individual helper files for pfcwd …

[202405] [PR #17914] Support for new snappi model (#17914)

---

ansible/roles/test/files/ptftests/py3/advanced-reboot.py
ansible/roles/test/files/ptftests/py3/wr_arp.py
ansible/roles/vm_set/library/vm_topology.py
tests/acl/test_acl.py
tests/acl/test_stress_acl.py
tests/qos/qos_sai_base.py
tests/sflow/test_sflow.py

```
8b16a64e0 (HEAD -> sync/202503, origin/sync/202503) Merge remote-tracking branch 'az_upstream/202412' into sync/202503
fe0ac4a2c (az_upstream/202412) Merge branch '202411' of https://github.com/sonic-net/sonic-mgmt into 202412
5c0cad1dc Use is_alive over isAlive for py3 threads (#18213) (#18469)
b7f49b2a6 [action] [PR:16972] Update the sflow test to pass on the t0 topo which does not have portchannel (#307)
64ecd5c93 Merge branch '202411' of https://github.com/sonic-net/sonic-mgmt into 202412
da50df84b Fix the generate_golden_config_db for multi-asic devices (#18138)
a52cceb87 [action] [PR:18444] support t1-isolated-d56u2 in test_acl.py, test_stress_acl.py and test_qos_sai (#305)
fa05606c1 fix bfd multihop test issue (#18370) (#18403)
c1f8f0f28 [action] [PR:18289] Fix ACL tests for …
```

[202503] Code sync Azure/sonic-mgmt.msft:202412 => 202503

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Summary:
Add hwsku Mellanox-SN5640-C512S2 into sonic-mgmt
Fix couldn't find interface error during add-topo:
Run add-topo on physical testbed, not seeing interface errors anymore.

[port_utils]: Add SKU Mellanox-SN5640-C512S2 (#18201)

---

tests/bgp/conftest.py

Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18669/

[202503] [BGP Tests] Enable Tests for LT2 and FT2 Topologies#18669

---

tests/common/testbed.py

* Support new testbed type LT2/FT2/UT2
* 
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18442

[202503] Support new testbed type LT2/FT2 (#18442)

---

ansible/group_vars/sonic/variables
ansible/module_utils/port_utils.py

Fix couldn't find interface error during add-topo
Ran add-topo on physical testbed without seeing errors.
Any platform specific information?
str4-sn5640-3
Supported testbed topology if it's a new test case? SN5640-C448O16

Add sku Mellanox-SN5640-C448O16 to port utils (#18223)

---

tests/qos/files/mellanox/qos_param_generator.py
tests/qos/files/mellanox/special_qos_config.yml
tests/qos/qos_sai_base.py

Summary:
Added SPC5 to the supported ASIC types.
Cherry pick of https://github.com/sonic-net/sonic-mgmt/pull/17908
Enable SPC5 on qos tests
Added the spc5 to the supported ASIC list.
Ran the qos tests on spc5 platform.
supproting spc5

[QoS] Added Spectrum-5 as supported ASIC

---

tests/common/cisco_data.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/qos/qos_sai_base.py
tests/qos/test_oq_watchdog.py
tests/saitests/py3/sai_qos_tests.py

Double commit https://github.com/sonic-net/sonic-mgmt/pull/18937

[202405] New test case for OQ watchdog

---

ansible/module_utils/port_utils.py

Cherrypick port_utils changes from PR#18487, PR#19094 and other related config updates for the 7060X O128 SKUs

7060X O128 sku port_utils cherrypick

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Sync PR #18017 from sonic-net/sonic-mgmt to 202412.
Original PR: https://github.com/sonic-net/sonic-mgmt/pull/18017

[202412][PR:18017] Add certain error signatures to loganalyzer ignore list

---

ansible/module_utils/port_utils.py
tests/common/helpers/constants.py

Cherry-pick the following:
- https://github.com/sonic-net/sonic-mgmt/pull/19178
- https://github.com/sonic-net/sonic-mgmt/pull/19179

[202503] cherry pick 19179 19178

---

ansible/vars/topo_t0-isolated-d256u256s2.yml
ansible/vars/topo_t0-isolated-v6-d256u256s2.yml
ansible/vars/topo_t1-isolated-d448u15-lag.yml
ansible/vars/topo_t1-isolated-v6-d448u15-lag.yml
ansible/veos
tests/acl/test_stress_acl.py
tests/qos/qos_sai_base.py

Cherry-pick: https://github.com/sonic-net/sonic-mgmt/pull/19211 into 202412.
Summary:
Update full topology for both C512S2 and C448O16 hwsku.
Update the t0-isolated-xx and t1-isolated-xx full topo
generated the topo again.

[202412][PR: 19211] update full isolated topo for C512S2 and C448O16

---

setup-container.sh
tests/common/plugins/conditional_mark/issue.py

[202412]manual cherry pick PR 19116 to Fix github api rate limit issue
https://github.com/sonic-net/sonic-mgmt/pull/19116

[202412]manual cherry pick PR 19116 to Fix github api rate limit issue

---

tests/common/helpers/platform_api/sfp.py
tests/platform_tests/api/test_sfp.py

Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/18938 to 202412 branch.

(202412) Fix txvr tests after diagnostic table restructuring

---

tests/common/gu_utils.py
tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
tests/conftest.py
tests/generic_config_updater/conftest.py

Sync PR #15182 from sonic-net/sonic-mgmt to 202412.
Original PR: https://github.com/sonic-net/sonic-mgmt/pull/15182

[202412][PR:15182] [GCU] [MA] Adding support in existing tests - Common changes 

---

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt

Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/19479

chore: disable swss loganalyzers for DT2#19479

---

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

Skip test bgp queue due to issue #18349
Add skip to conditional marks
Run test, test skipped
---------

Skip bgp queue tests due to issue 18349 (#18372)
