Azure/sonic-mgmt.msft

tests/common/plugins/sanity_check/__init__.py, tests/common/plugins/sanity_check/recover.py
Summary: Fixes # (issue)
Sometimes exabgp in ptf would be in incorrect status by stress testing, hence add restarting exabgp before re-announce routes in sanity check.
1. Restart exabgp before re-announce routes
2. Add try catch to handle failed to re-announce issue
Run test with sanity check
=> [sanity_check][bgp] Enhance sanity check recover for bgp default route missing (#16357)

tests/saitests/py3/sai_qos_tests.py
In #8149 the `multi-asic` and `multi-dut` variants were added to `test_qos_sai.py`. This required updating calls to `dynamically_compensate_leakout` to specify either the `src_client` or dst_client`but a couple calls in`PGSharedWatermarkTest` passed the wrong client.
For more details on the failure this causes see #16167
Summary: Fixes #16167
=> Correcting client arguments to dynamically_compensate_leakout (#16169)

tests/qos/qos_sai_base.py, tests/saitests/py3/sai_qos_tests.py
We are seeing UnboundLocalError when running sonic-mgmt tests against a single-ASIC linecard:
```
UnboundLocalError: local variable 'dst_sys_port_id' referenced before assignment
```
Upon further investigation, this was determined to be happening because a previous attempt to fix this issue (PR #13700) completely omitted the ASIC prefix, but the entries in SYSTEM_PORT in config_db do have an Asic0 prefix even on a single ASIC DUT.
Resolve this by specifically adding the Asic0 prefix in the case of a single-ASIC T2 DUT, instead of leaving the prefix out.
Tested by manually running qos tests on a T2 single ASIC DUT with these changes.
=> sonic-mgmt: Fix namespace issues for qos tests on T2 single ASIC (#15708)

tests/common/snappi_tests/common_helpers.py, tests/snappi_tests/pfc/files/mixed_speed_multidut_helper.py, tests/snappi_tests/pfc/test_pfc_mixed_speed.py, tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py, tests/snappi_tests/variables.py
As part of the new testcases to be added for the PFC-ECN, this PR addresses the mixed-speed ingress and egress testcases.
Summary: Fixes # (issue) #13655 #13215
This script addresses the mixed speed testcases. The topology has single ingress and egress of 400Gbps and 100Gbps respectively. The congestion is caused due to three factors:
* Due to oversubscription of egress.
* Pause frames received on egress link of 100Gbps.
* Both - over-subscription of egress and pause frames received on egress.
Idea is to test behavior of the DUT in these conditions.
The port_map defines to choose single ingress of 400Gbps and egress of 100Gbps.
Following test functions are used:
1. **test_mixed_speed_diff_dist_dist_over:**
Lossless and lossy traffic are sent at 88 and 12% of the line-rate (400Gbps) …
=> [Snappi]: PFC - Mixed Speed testcases (#14122)

tests/snappi_tests/pfc/files/pfc_congestion_helper.py, tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py, tests/snappi_tests/pfc/test_pfc_port_congestion.py, tests/snappi_tests/pfcwd/files/pfcwd_actions_helper.py, tests/snappi_tests/pfcwd/test_pfcwd_actions.py
This pull-request has changes specifically for the following commit-IDs: [a82b489](https://github.com/sonic-net/sonic-mgmt/commit/a82b4892442c69b9e44ccd309b5b3e6069363c5f) [180af4d](https://github.com/sonic-net/sonic-mgmt/commit/180af4dd68791fa453f795b77f426773d58b1f59) [3da40bc](https://github.com/sonic-net/sonic-mgmt/commit/3da40bc5503ded7bb063c369352eb8bd2123a148)
This PR specifically handles the testcases pertaining to the new PFC-ECN testplan added.
Summary: Fixes # (issue) #13655 #13215
Three test-scripts have been added to specifically test: non-congestion scenarios (line-rate tests), congestion testcases via over-subscription and PFCWD (drop and forward mode).
1. Test case has dictionary called test_def which defines various testcases parameters necessary to run the testcase. An …
=> [Snappi] New testcases for PFC-ECN. (#13865)

tests/common/snappi_tests/snappi_test_params.py, tests/common/snappi_tests/traffic_generation.py
67989d1312b1778681d6575b12b66aa42fdf05a7
Please review the commit-ID given above.
Original PR13655 was raised to add the new testcases. However, manage the changes efficiently, it was decided to split the original into three PRs for ease in review process.
This PR tracks are the infrastructure related changes required for the execution of the testcases.
Note - PR #13848 needs to be merged in first before this PR is merged.
Summary: Fixes # (issue) #13655 #13215
This PR tracks only the infrastructure related changes needed for addition of the new testcases.
Important changes are listed below:
Change directory - tests/common/snappi_tests/
1. Additional member variable 'base_flow_config_list' is added as list to class 'SnappiTestParams' in snappi_test_params.py file to accommodate for …
=> [Snappi] Infra changes for new PFC-ECN testcases. (#13864)

tests/common/reboot.py
Summary: Fixes #16289 + merges #16581 to remove double reboot bug
REBOOT_TYPE_POWEROFF reboot causes test failures on T2 as NTP slew doesn't recover for a while
Skip dut uptime check on reboot for REBOOT_TYPE_POWEROFF reboot on T2
Was previously casing test_power_off_reboot.py to fail, no longer causing it to fail
N/A
N/A
=> Use alternate check for reboot for T2 after reboot with REBOOT_TYPE_POWEROFF (#16348 + #16581)

tests/pfcwd/test_pfcwd_function.py
Summary: Fixes the following error per discussion in #16535
`UnboundLocalError: local variable 'PFC_STORM_TIMEOUT' referenced before assignment`
fix syntax error in test_pfcwd_function.py:
passed on msn2700. failed on 8102.
=> fix UnboundLocalError in test_pfcwd_function.py (#16631)

tests/bfd/test_bfd_static_route.py, tests/drop_packets/drop_packets.py, tests/snmp/test_snmp_queue_counters.py
Summary: Fixes MSFT PBI#30938349
1. Ignore the err logs during loganalyzer analyzer on config_reload and reboot, so that we can enable log analyzer on other codes beyond config reload/reboot, rather than skip on all of the test module.
2. Ignore err logs in bfd_static_route tests
1. Ignore the err logs during loganalyzer analyzer on config_reload and reboot, so that we can enable log analyzer on other codes beyond config reload/reboot, rather than skip on all of the test module.
2. Ignore err logs in bfd_static_route tests
Verified on physical chassis testbeds
=> [Chassis] ignore log analyzers on config reload/reboot, and bfd test (#16625)

tests/common/config_reload.py, tests/common/plugins/loganalyzer/loganalyzer.py, tests/common/plugins/loganalyzer/utils.py, tests/common/reboot.py
Summary: Fixes #7313
Fix the bug that run with --disable_loganalyzer
1. Always remove ignore_loganalyzer from the original kwargs
2. Rename to a more correct name
Tested on physical T2 testbeds
=> [loganalyzer] Fix the bug of ignore_loganalyzer decorator (#16624)

tests/qos/test_qos_sai.py
In continuation of the PR #14469, adding the fixture to few more tests in test_qos_sai.
Summary: Fixes # (issue)
=> [Qos] Adding lacp_timer fixture to few more tests (#16224)

tests/platform_tests/test_cpu_memory_usage.py
Summary: Fixes #16104
We wish to increase the mem threshold for Arista 7800 devices to 90 in order to help the platform_tests pass.
Modified the threshold in `tests/platform_tests/test_cpu_memory_usage.py`
Pending testing
=> [chassis][Arista] Increase mem threshold for arista 7800 devices (#16105)

tests/voq/test_voq_chassis_app_db_consistency.py
Summary: Fixes # (issue) Due to LAG ID SET Changes [sonic-net/sonic-buildimage#20369](https://github.com/sonic-net/sonic-buildimage/pull/20369). The Test Case Expectation and Assertion need to be changed.
Changes by the Functionality [sonic-net/sonic-buildimage#20369](https://github.com/sonic-net/sonic-buildimage/pull/20369) of Lag ID assignment. The TC Expectation and assertion is changed
Ignoring the SYSTEM_LAG_ID_SET to be same as in case pre-dump. But rather be assigned from `SYSTEM_LAG_IDS_FREE_LIST` in order. Added a sanity of lag_id_set to ensure the functionality of PR [sonic-net/sonic-buildimage#20369](https://github.com/sonic-net/sonic-buildimage/pull/20369).
Tested and Verified on a T2 VOQ Chassis
=> [Chassis][voq] TC test_voq_chassis_app_db_consistency.py Modification Due to Lag ID Set Changes (#16116)

tests/voq/test_fabric_cli_and_db.py
Summary: Fix the fabric_cli_and_db test so it only tests connected links. Fixes # (issue)
The fabric_cli_and_db failed in cases where the test selected a link that was not connected. This issue occurred because the portList set was not reset for each chip, allowing links that were connected on other chips to be tested, even though they were not connected on the chip being tested. In this PR, the portList is reset for each chip, and the 'show fabric reachability' command is also run on each chip. As a result, the test now only choose connected links on the chip under test.
=> Fix fabric_cli_and_db so it only tests on connected links. (#16309)

tests/pfcwd/test_pfcwd_function.py
Summary:
We need to verify the new code before enabling it for cisco-8000. For now, we are temporarily disabling it.
Temporarily remove cisco-8000 from using the new code for mellanox.
Removed the cisco-8000 string from the supported list.
```
=========================================================================================================== PASSES ===========================================================================================================
_______________________________________________________________________________________ TestPfcwdFunc.test_pfcwd_actions[croc-t1-dut] ________________________________________________________________________________________
______________________________________________________________________________________ …
```
=> Temporarily remove cisco-8000 from pfcwd/PFC_STORM_TIMEOUT. (#16661)

tests/common/devices/eos.py, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py
Intermittently testQosSaiLossyQueue tests fails due to Port-channel flap on broadcom-dnx T2 Voq chassis. The reason the port-channel goes down is because this test requires disabling TX on the egress port (which is a member of a port-channel) With the huge buffer-size, it takes a longer time to send packets . This will result in the TX LACP packets to stop egressing, so after 3 LACP packets are missed (~90s) on the server side the LAG is torn down.
Issue # #11682 Summary: Fixes # (issue)
Intermittently testQosSaiLossyQueue tests fails due to Port-channel flap
The lacp timer multiplier on the EOS host is configurable. By default, timeout is 30 secs with a failure tolerance of 3. We changed the multiplier to an increased value to hold the connectivity for some time until all packets are …
=> [CHASSIS][Voq][QoS]Increasing LACP timer for lag ports for broadcom-dnx neighbor EOS host (#14469)

tests/bgp/route_checker.py, tests/bgp/test_reliable_tsa.py, tests/bgp/test_seq_idf_isolation.py, tests/bgp/test_startup_tsa_tsb_service.py, tests/bgp/test_traffic_shift.py
Summary: Partially tackles #16577
Tests are flaky, sometimes failing on `verify_only_loopback_routes_are_announced_to_neighs`: `Failed to verify routes on nbr in TSA`
Add a function wrapping `verify_only_loopback_routes_are_announced_to_neighs` with wait_until and assert to allow time for neighbor to update routes
These logs were seen in passed tests, showing that wait_until helps avoid false negatives
```
17/01/2025 05:42:18 utilities.wait_until                     L0153 DEBUG  | verify_only_loopback_routes_are_announced_to_neighs is False, wait 10 seconds and check again
05:42:12 route_checker.verify_loopback_route_with L0014 INFO   | Verifying only loopback routes are announced to bgp neighbors
05:42:18 parallel.on_terminate                    L0085 INFO   | process …
```
=> Add function to wrap verify_only_loopback_routes with assert and wait_until (#16523)

tests/pfcwd/conftest.py, tests/pfcwd/test_pfcwd_function.py
Summary: pfcwd_multi_port test failed when using the longer PFC_STORM_TIMEOUT seconds. We found this is due to fake-storm flag. After disabling the fake-storm, the test is passing.
Enabling the longer pfc storm timeout and disabling fake-storm for cisco-8000.
Enabled the if conditions for mellanox to include cisco-8000.
Ran it on my TB, verified on 8102, 8111 and T2:
8102 run log:
```
collected 5 items                                                                                                                                                                                                            
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[mth-t0-64] PASSED …
```
=> [#16695] pfcwd: Set fake-storm false for cisco platforms. 

tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
Summary: In the function: save_restore_config() in test_multidut_pfcwd_basic_with_snappi.py, the teardown section copies back the backup files to /etc/sonic/. But the next line is to save config, which is not right. This PR fixes this issue.
The backup files contain the original configs for the DUT, but the config save command will overwrite them. In teardown, we want the original configs back, not the running configs.
Remove the config-save command in teardown.
Ran it on my TB. I checked if the running config is different from saved config, and verified the new code works correctly.
=> [PR:16691]T2:snappi_tests:Don't save config after copying over the backup files. 

ansible/config_sonic_basedon_testbed.yml, ansible/fanout_connect.yml, ansible/library/announce_routes.py, ansible/library/test_facts.py, ansible/library/testbed_vm_info.py, ansible/module_utils/multi_servers_utils.py, ansible/plugins/filter/filters.py, ansible/roles/eos/tasks/main.yml, ansible/roles/fanout/templates/arista_7260_connect.j2, ansible/roles/vm_set/library/vm_topology.py, ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/announce_routes.yml, ansible/roles/vm_set/tasks/create_dut_port.yml, ansible/roles/vm_set/tasks/get_dut_port.yml, ansible/roles/vm_set/tasks/main.yml, ansible/roles/vm_set/tasks/remove_topo.yml, ansible/testbed-cli.sh, ansible/testbed.yaml, ansible/testbed_add_vm_topology.yml
Sync PR #15643 from sonic-net/sonic-mgmt to 202412.
> ### Description of PR
> Summary: Fixes # (issue) In PR #15547, we define server index in topology file which make topology file and testbed yaml file is coupled. To decouple them, in new design #15395, we remove server index in topology file and add dut_interfaces in testbed yaml, so there is no more change on topology file schema.
> 
> ### Type of change
> * [ ]  Bug fix
> * [x]  Testbed and Framework(new/improvement)
> * [ ]  Test case(new/improvement)
> 
> ### Back port request
> * [ ]  202012
> * [ ]  202205
> * [ ]  202305
> * [ ]  202311
> * [ ]  202405
> 
> ### Approach
> #### What is the motivation for this PR?
> Decouple topology file and testbed file in design.
> 
> #### How did you do it?
> Record all information in testbed …
=> [202412][PR:15643] [testbed-cli] Code change on add-topo and deploy-minigraph for deploying testbed with peers on multiple servers

tests/voq/fabric_data/Arista-7804R3-FM.yaml, tests/voq/fabric_data/Arista-7808R3A-FM.yaml, tests/voq/fabric_data/Nokia-IXR7250E-SUP-10.yaml, tests/voq/test_fabric_reach.py
The original test used a base moduleID offset for Arista devices, however, this offset created mismatch in the moduleID and led the test to fail.
Remove the base module ID offset variable: supervisorAsicBase
I ran the test successfully on a T2 testbed to verify the change.
Summary:
Cherry picked from https://github.com/sonic-net/sonic-mgmt/pull/15828
=> [Cherry-pick][msft-202405] Remove supervisorAsicBase offset from test_fabric_reach.py

tests/tacacs/test_accounting.py, tests/tacacs/utils.py
Use number of logs instead of timestamp in `change_and_wait_aaa_config_update`
https://github.com/sonic-net/sonic-mgmt/pull/16723
=> [msft-202405 cherry-pick] Use number of logs instead of timestamp fix

tests/common/fixtures/duthost_utils.py
Description of PR
Summary:
Fixes #16436, caused by added BGP check in #15936, which doesn't account for T2 BGP time to come up
Approach
Function wait_bgp_sessions timeout is too short for T2, fails in test_mgmt_ipv6_only test suite causing a fixture to error wrongly and not teardown properly leaving TB in bad state without ipv4 mgmt ip
Increase timeout to 900s from 120s if duthost it is checking is supervisor
Run locally on T2
See for passing test:
17/01/2025 07:34:39 utilities.wait_until                     L0153 DEBUG  | check_bgp_session_state_all_asics is False, wait 10 seconds and check again
17/01/2025 07:34:49 utilities.wait_until                     L0135 DEBUG  | Time elapsed: 164.073392 seconds …
=> Increase timeout for wait_bgp_sessions for T2 duts (#16438)

.github/workflows/autosync_pub_msft.yml
In this PR, we setup a github action to auto sync for branches 202405 and 202412 from sonic-net/sonic-mgmt to Azure/sonic-mgmt.msft. 
Summary:
In this PR, we setup a github action to auto sync for branches 202405 and 202412 from sonic-net/sonic-mgmt to Azure/sonic-mgmt.msft. 
Sync code from sonic-net/sonic-mgmt to Azure/sonic-mgmt.msft and them, open a pull request. 
For test, I use my own repo, I syncd the code from sonic-net/sonic-mgmt to my personal repo. 
You can refer to 
Github action: https://github.com/yutongzhang-microsoft/sonic-mgmt/actions/runs/13365460642/job/37322204980
PR: https://github.com/yutongzhang-microsoft/sonic-mgmt/pull/4
=> Setup github actions to auto sync from public to msft. 

.github/workflows/autosync_pub_msft.yml
Due to the current settings of Azure/sonic-mgmt.msft, the GitHub Actions token only has read permissions. Therefore, we need to explicitly define the required permissions for the workflow.
Summary:
Due to the current settings of Azure/sonic-mgmt.msft, the GitHub Actions token only has read permissions. Therefore, we need to explicitly define the required permissions for the workflow.
Explicitly define the required permissions for the workflow
Changed the settings in my own repo, and test.
=> Explicit permission requirement for gihub actions token in autosync workflow. 

tests/gnmi/test_gnmi.py
Summary:
ADO: 30909878
- [x ] 202012
- [x ] 202205
- [x ] 202305
- [x ] 202311
- [x ] 202405
Replacing rand_one_dut_hostname with enum_rand_one_per_hwsku_hostname
Ran on testbeds in Microsoft Lab
=> Running test_gnmi.py on each hwsku instead of selecting one rand hwsku

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/plugins/ptfadapter/__init__.py, tests/common/plugins/ptfadapter/ptfadapter.py, tests/srv6/srv6_utils.py, tests/srv6/test_srv6_dataplane.py
Cherry-pick PR for PR#16660 in sonic-mgmt repo.
Test SRv6 dataplane uN and uN +USD behavior
Summary:
=> Test SRv6 dataplane uN behavior (#16660)

ansible/group_vars/ptf/secrets.yml, ansible/group_vars/ptf_host/secrets.yml, ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/announce_routes.yml, ansible/roles/vm_set/tasks/ptf_change_mac.yml, ansible/roles/vm_set/tasks/ptf_portchannel.yml, ansible/roles/vm_set/tasks/renumber_topo.yml, ansible/roles/vm_set/tasks/start_ptf_tgen.yml, ansible/roles/vm_set/tasks/update_ptf_password.yml, ansible/veos_vtb, tests/scp/test_scp_copy.py
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/16457 to 202405 branch.
The PTF container is always using default password. If the PTF container is on same bridge with the host server's management IP, then it is easily accessible from other host servers. This is not secure enough. We need to support alternate password for the PTF container and password rotation.
This change improved the ansible related code to support accessing the PTF containers using the multi_ssh_pass ansible plugin. Then we can specify alternate passwords for the PTF container. When alternate passwords are specified, the default password of PTF container is updated after PTF creation.
Tested remove-topo/add-topo/restart-ptf on …
=> Support alternate password for PTF container (#16457)

tests/gnmi/test_gnmi.py
Reverts Azure/sonic-mgmt.msft#95
=> Revert "Running test_gnmi.py on each hwsku instead of selecting one rand hwsku"

tests/acl/test_acl.py, tests/qos/qos_sai_base.py
Sync PR #16964 from sonic-net/sonic-mgmt to 202412.
Original PR: https://github.com/sonic-net/sonic-mgmt/pull/16964
=> [202412][PR:16964] Update acl and qos script for topology t1-isolated-d28u1 t0-isolated-d16u16s1 and t0-isolated-d16u16s2

tests/srv6/srv6_utils.py, tests/srv6/test_srv6_dataplane.py, tests/srv6/test_srv6_static_config.py
Cherry-pick PR
Summary: In daily operations, the switches may perform configuration reloading or BGP service restart to recover from transient failures. We need to add test cases to verify that SRv6 functionalities work correctly after the recovery.
Summary:
=> Additional test cases that verify the reliability of SRv6 functionalities (#17133)

tests/qos/qos_sai_base.py
Cherry pick sonic-mgmt #17393
Summary:
After https://github.com/sonic-net/sonic-utilities/pull/3792, we need to disable pfcwd on backplane ports. 
PFCWD needs to be disabled on backplane ports when running qos_sai testing
added module level fixture to disable pfcwd
TBD
=> [PR:17393][202405] disable pfcwd before running qos_sai testing.

tests/common/fixtures/fib_utils.py
This is a cherry-picked PR with resolved auto merge conflict issue to merge test_fib changes already delivered to master, targeting 202411 branch.
Summary:
Fixes #31598080 fib/test_fib.py spend long time
duthost.fetch can cause significant delays in the test and this PR replaces it with duthost.fetch_no_slurp, where we observe dramatic save in time during the test.
Before the change, it caused 10 mins per fetch per ASIC in Cisco T2 chassis, where as the fix reduced this time down to ~3seconds per fetch per ASIC. Since we have 3 ASICs per LC and 3 LCs in DUT, this fix will theoretically save 5373s/89.55mins per test, which is 99.5% reduction in fetch time.
Before:
22/02/2025 23:04:02 base._run L0071 DEBUG | /var/src/sonic-mgmt_xxx/tests/common/fixtures/fib_utils.py::get_t2_fib_info#66: …
=> [manual] [PR:17385] Fix duthost.fetch causing delays in the test_fib

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Due to a Jira, temporarily skipping few testcases in platform_tests/api/test_thermal.py and test_thermal_state_db.py. Will revert it as soon as the jira is fixed
Summary:
Due to a Jira, temporarily skipping few testcases in platform_tests/api/test_thermal.py and test_thermal_state_db.py. Will revert it as soon as the jira is fixed
Skip in conditional_mark file
SKIPPED [9] platform_tests/api/test_thermal.py: Unsupported platform API in mellanox. Skip in case of Cisco platform for T2 profile due to temperarory bug.
Cisco 8808 chassis and T2 profile
=> Temporarily skipping few testcases in platform_tests/api/test_thermal.py and test_thermal_state_db.py for cisco devices

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Temporarily ignore certain log messages. Fix for it will be available soon and we will revert this PR back
Summary:
Ignore TAM errors. They are not impacting any functionality
Add Log messages to LA ignore file
=> Temporarily Ignore certain error message

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Summary:
Enable pipe dscp tests on decap tests, and disabled uniform dscp tests.
To support SRv6 requirement, we had to move our platforms to pipe mode from uniform. Based on this we might have to slightly change the skip condition.
vxlan set_unset flow will use default tables and not load new ipinip test tables(default mode is now pipe and the test thinks its uniform) https://github.com/sonic-net/sonic-mgmt/pull/5834
. In the vxlan disable scenario, the entire ipinip json file is removed and replaced. So hence we are seeing this failure only in set_unset.
Skip unsupported tests and enable supported.
Updated skip condition
Ran CI to verify.
SPC4/5 only.
=> Skipped decap tests with uniform dscp, Enabled pipe dscp tests

tests/common/snappi_tests/snappi_fixtures.py, tests/common/snappi_tests/traffic_generation.py, tests/snappi_tests/conftest.py, tests/snappi_tests/ecn/files/helper.py, tests/snappi_tests/ecn/test_ecn_marking_with_snappi.py
Summary:
For cisco-8000, if the traffic flows to a connected route, the system uses the default voq. If we use static route, it uses the split-voq. In this PR, we change the dest IP address of the traffic streams to a static routed destination, and add that static route as well in the DUT. To test it, we have used the ECN script, and had to modify it as well.
In ECN we keep hitting the drop or other limits before hitting the xoff limits, due to the default voq. So changing it to static route helps in passing the tests.
Hitting failures in multiple tests due to traffic taking default voq (due to the connected routes).
Added a new function to add static route in DUT, and use the new IP destination value for the traffic stream.
Alpesh had run the code in 202405 in my TB.
Only …
=> Porting 17012 to sonic-mgmt.msft/202405: Static route ixia

tests/platform_tests/api/test_sfp.py
Summary: 
Update xcvr info keys based on PR https://github.com/Azure/sonic-platform-common.msft/pull/69.
The change is not related to SFP cable.
Allign the test with latest changes
Executed test test_get_transceiver_info on setup with different cable.
=> [API transceiver_info] update xcvr info keys

tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Reverts Azure/sonic-mgmt.msft#154
=> Revert "Temporarily skipping few testcases in platform_tests/api/test_thermal.py and test_thermal_state_db.py for cisco devices"

ansible/group_vars/sonic/variables, ansible/library/announce_routes.py, ansible/module_utils/port_utils.py, ansible/vars/topo_Nokia-IXR7250-X3B.yml, ansible/vars/topo_t2_single_node_max.yml, ansible/vars/topo_t2_single_node_min.yml
Summary:
This PR enhances the VLAN parsing logic to correctly handle non-chassis T2 devices. The assumption is for non-chassis T2 setups.
port the changes from #17311 
And Changes for the generation of minigraph for non-chassis T2 setups
This PR adds a clear handling mechanism for non-chassis T2 by setting dut_index = 0.
And changes for the Minigraph generation non-chassis T2 setups
Verified with:
Non-chassis VOQ T2 devices & T2 VOQ Chassis devices
=> Introducing changes for minigraph generation and add topo to work for single node T2 (#17986)

.github/workflows/autosync_pub_msft.yml
We miss a `"` at the end of the script `autosync_pub_msft.yml`. In this PR, we fix this issue.
=> Fix missing quote in autosync_pub_msft.yml script

tests/qos/files/mellanox/qos_param_generator.py, tests/qos/files/mellanox/special_qos_config.yml, tests/qos/qos_sai_base.py, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_base_test.py, tests/saitests/py3/sai_qos_tests.py
1. For spc4 and above, there is only the lossy buffer, so the buffer for the lossless buffer will be taken by the lossy buffer. If the packet size is too small, the packet number sent to occupy the shared buffer will increase a lot, which will lead to the descriptor being exhausted, so update testQosSaiPgSharedWatermark, testQosSaiQSharedWatermark, and testQosSaiLossyQueue accordingly.
2. Remove the test config of scheduler.block_data_plane, otherwise it might raise yang validation error when do config reload
3. When there is no lossless buffer, return a dump buffer lossless pg profile, and skip tests related to lossless buffer case dynamically
4.  Skip fixture reaseAllports for mellanox device, because after qos test is finished, the teardown will do config reload, it will restore the …
=>  Update qos sai due to no lossless pg for some platforms 

tests/common/fixtures/duthost_utils.py, tests/common/plugins/sanity_check/checks.py
Summary:
Fixes sanity check for isolated-v6 which is ipv6 only topology
support ipv6 only topology in sanity check.
- check ip_interface for IPv4 only.
- check bgp router id same as loopback0 for IPv4 only.
- check v4_default_route only when there are IPv4 BGP neighbors.
Test passed on local testbed.
=> [PR: 18083][202412] fix sanity check for ipv6 only topo 

ansible/library/conn_graph_facts.py, ansible/templates/minigraph_link_meta.j2
Conflict fix https://github.com/sonic-net/sonic-mgmt/pull/17295
Description of PR
Summary: Add option to toggle on FEC for minigraph in ixia topo Fixes # (issue) 31623287
Approach
When in ixia FEC enabled port doesn't work well in some breakout ports. We want an option to force turn off FEC.
To use it, modify the links file. For example suppose we have the original _links.csv:
StartDevice,StartPort,EndDevice,EndPort,BandWidth,VlanID,VlanMode,AutoNeg str-msn2700-01,Ethernet0,str-7260-10,Ethernet1,40000,1681,Access,on str-msn2700-01,Ethernet4,str-7260-10,Ethernet2,40000,1682,Access,on str-msn2700-01,Ethernet8,str-7260-10,Ethernet3,40000,1683,Access,on str-msn2700-01,Ethernet12,str-7260-10,Ethernet4,40000,1684,Access,on …
=> feat: add option to toggle on FEC in minigraph (#17295)

tests/gnmi/conftest.py, tests/gnmi/helper.py
During our recent nightly runs, we observed failures in the gNMI tests due to the DUT time being out of sync with the NTP server. To address this, we’ve updated the time synchronization function to ensure the DUT time is aligned with the NTP server, and we now invoke this function prior to calling setup_gnmi_server.
Microsoft ADO: 32627324
=> Adding fix for gnmi tests to sync dut time with NTP Server

tests/common/reboot.py
Summary:
Double commit https://github.com/sonic-net/sonic-mgmt/pull/18001
test_pfcwd_basic_single_lossless_prio_reboot failed due to dshell initialization.
Fix the failures caused by dshell initialization.
If cisco-8000, wait dshell ready after reboot.
Tested it on T2 testbed.
```
23:44:54 base._run                                L0108 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#136: [yy39top-lc4] AnsibleModule::command Result => {"changed": true, "stdout": "PFC support is enabled on the device\nSQG counters:\n   SQG 0: 0          (0x0)\n   SQG 1: 0          (0x0)\n   SQG 2: 0          (0x0)\n   SQG 3: 0          (0x0)\n\nTC counters (global):\n   CTC 0: 0          (0x0)\n   CTC 1: 0          (0x0)\n   CTC 2: 0          (0x0)\n   CTC 3: 0 …
```
=> [202405] MIGSMSFT-965 T2 failures in test_pfcwd_basic_with_snappi.py reboot cases

tests/pfcwd/cisco/default_pfc_time.py, tests/pfcwd/cisco/set_pfc_time.py
Summary:
The pfc-512bit script was working in previous builds, but fails in later builds. It started giving the unknown variable error. This is because the later images have stopped the auto-import of the variables used in the scripts.
Approach
Pls see description.
Added the new import in the scripts.
Ran the failing test on T2 TB:
====================================================================================================================== warnings summary ====================================================================================================================== ../../usr/local/lib/python3.8/dist-packages/paramiko/transport.py:236 …
=> Include import in the timer setup scripts for pfcwd. (#18198)

tests/voq/test_voq_fabric_capacity.py
Manually porting PR15994: https://github.com/sonic-net/sonic-mgmt/pull/15994 to msft-202503
=> [msft-202503] Add test_voq_fabric_capacity.py

tests/srv6/test_srv6_vlan_forwarding.py
Cherry-pick PR for #17861 in sonic-mgmt.
Summary: This is to add a test case to verify that after enabling proxy_arp, there is no L2 flooding in downstream VLAN even though the switch does not have a FDB entry to forward a downstream SRv6 packet.
=> Add test_srv6_uN_no_vlan_flooding test case (#17861)

ansible/config_sonic_basedon_testbed.yml, ansible/library/generate_golden_config_db.py
Summary:
Update default_pfcwd_status to disable for some platform which only have lossy traffic. 
Note: This PR needs the image fix https://github.com/sonic-net/sonic-utilities/pull/3880 for it to work.
Update the default pfcwd status in golden_config for lossy platform
Update the default pfcwd status in golden_config for lossy platform
Verified on physical platform.
=> [202412][PR: 18350] disable default pfcwd for all lossy DUT

tests/acl/test_acl.py, tests/common/dualtor/dual_tor_utils.py, tests/common/plugins/ptfadapter/README.md, tests/decap/test_subnet_decap.py, tests/dualtor/test_ipinip.py, tests/dualtor/test_tor_ecn.py, tests/everflow/test_everflow_ipv6.py, tests/everflow/test_everflow_per_interface.py, tests/everflow/test_everflow_testbed.py, tests/route/test_static_route.py
When running nightly tests using the t2_single_node_min topology, we encountered failures in the ACL test. The root cause was a hardcoded call to get_mac(0, 0), which assumes that a device with device_number = 0 and port_number = 0 exists. This assumption does not hold true in some topologies like t2_single_node_min.
Instead of using the hardcoded (0, 0) port index, this PR dynamically selects the first available port from the existing list of ports. This improves compatibility and prevents test failures across topologies with varying port configurations.
Tested locally by running acl/test_acl.py against the t2_single_node_min topology and confirmed that the tests pass successfully.
=> Fix the hardcoded interface issue in PTF (#17965)

ansible/config_sonic_basedon_testbed.yml, ansible/library/announce_routes.py, ansible/library/generate_golden_config_db.py, ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/snappi_tests/snappi_fixtures.py, tests/route/test_route_perf.py, tests/snappi_tests/bgp/files/bgp_convergence_helper.py, tests/snappi_tests/bgp/files/bgp_test_gap_helper.py, tests/snappi_tests/bgp/test_bgp_convergence_performance.py, tests/snappi_tests/bgp/test_bgp_local_link_failover.py, tests/snappi_tests/bgp/test_bgp_remote_link_failover.py, tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py, tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py, tests/snappi_tests/bgp/test_bgp_scalability.py, tests/snappi_tests/lacp/files/lacp_dut_helper.py, tests/snappi_tests/lacp/files/lacp_physical_helper.py, tests/snappi_tests/lacp/test_add_remove_link_from_dut.py, tests/snappi_tests/lacp/test_add_remove_link_physically.py, tests/snappi_tests/lacp/test_lacp_timers_effect.py, tests/snappi_tests/reboot/files/reboot_helper.py, tests/snappi_tests/reboot/test_cold_reboot.py, tests/snappi_tests/reboot/test_fast_reboot.py, tests/snappi_tests/reboot/test_soft_reboot.py, tests/snappi_tests/reboot/test_warm_reboot.py, tests/vxlan/test_vnet_bgp_route_precedence.py
```
81505c88b (az_upstream/202412) Merge branch '202411' of https://github.com/sonic-net/sonic-mgmt into 202412
30b7d73b5 (pub_upstream/202411) [202411 ] Updating the BGP, Reboot and LACP  convergence cases to latest Snappi Api Model instead of Snappi_convergence module [ PR 18044 ] (#18391)
e146100de [action] [PR:18292] Fix Skip tests if no portchannels are found in prepare_test_port fixture (#280)
d8b9193aa [action] [PR:17985] [tests_mark_conditions.yaml]: Skip GNMI/ZMQ test for isolated topology (#281)
ef951e61f [action] [PR:17943] Add default routes to t1-isolated-d128 (#282)
2d3aec594 [action] [PR:18341] [route/test_route_perf] Support reading l3_alpm_template from config.bcm for TH5 platforms (#284)
6390c7dc9 [202412][PR: 18350] disable default pfcwd for all lossy DUT (#271) …
```
=> [202503] Code sync Azure/sonic-mgmt.msft:202412 => 202503

tests/acl/test_stress_acl.py
In the test case, the selected destination ports are uplink ports, and the dst ip for the test is using the "10.0.0.1", in the t1-isolated-d28u1, the 10.0.0.1 is the ip of the downlink, so the test will fail since it expect the traffic could be received on the uplink.
This is cherry-pick for https://github.com/sonic-net/sonic-mgmt/pull/16965
=> Align stress acl test for the t1-isolated-d28u1 topo (#16965)

tests/bgp/test_bgp_peer_shutdown.py, tests/bgp/test_bgp_update_timer.py
Manual cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/18441
test_bgp_peer_shutdown.py fails on UpperSpineRouter
Added handling for UpperSpineRouter in bgp_peer_shutdown test and other tests where similar check is done
Run bgp/test_bgp_peer_shutdown.py on device with dut_type UpperSpineRouter
=> Update neighbor type for upperspinerouter (#18441)

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/files/qos_params.j2c.yaml, tests/qos/test_qos_sai.py, tests/saitests/py3/sai_qos_tests.py
Cherry-pick  (#16885)
Verifying HeadroomPoolsize test for broadcom-dnx chassis
Executed qos test for headroomPool size and verify the results
=> [Cherry-pick #16885]HeadroomPoolSize test with dynamic_threshold based buffer allocation

ansible/library/generate_golden_config_db.py
There were some cherry pick conflicts for 202503 branch.
original PR: https://github.com/sonic-net/sonic-mgmt/pull/17556
Summary: The previous PR https://github.com/sonic-net/sonic-mgmt/pull/17024 changed the image version checking for BMP feature and provided a new API for overwriting features config in golden_config_db.json. However, the implementation was problematic and broke the setup for multi-asic virtual chassis.
=> Fix the generate_golden_config_db for multi-asic devices

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/qos/files/qos_params.j2c.yaml, tests/qos/test_qos_sai.py
os test params updated on top of PR #https://github.com/sonic-net/sonic-mgmt/pull/18324
With the new buffer- profile introduced in PR#https://github.com/sonic-net/sonic-buildimage/pull/22427 ,the qos params to verify qos test in sonic-mgmt is updated
Summary:
Type of change
Bug fix
Testbed and Framework(new/improvement)
New Test case
Skipped for non-supported platforms
Test case improvement
Back port request
202012
202205
202305
202311
202405
202411
Approach
Verify sonic-mgmt qos test with new buffer-profile
Executed sonic-mgmt qos tests & verified
Any platform specific information?
Supported testbed topology if it's a new test case?
=> [202503]QoS test params for j2c+ single_dut_multi_asic

tests/snmp/test_snmp_queue_counters.py
Description of PR
Summary:
32624894
Type of change
Bug fix
Testbed and Framework(new/improvement)
New Test case
Skipped for non-supported platforms
Test case improvement
Approach
Disable route check in snmp queue counter, fix the test failure on Cisco chassis
Disable route check in snmp queue counter
Run test on physical devices, and it passed.
=> Disable route check in snmp queue counter (#18485)

tests/common/snappi_tests/snappi_fixtures.py, tests/snappi_tests/conftest.py
Summary:
Recently https://github.com/sonic-net/sonic-mgmt/pull/17012 introduced static routes-based destinations for snappi tests.  That PR included a LA-error ignore fixture, since the static route introduced two LA errors during the runs. This PR removes this fixture, and updates the static route functions to completely remove the LA Error in the first place. The LA errors were: 
```
routeCheck' status failed .*", r".*missing interface entry for static route.
```
1. RouteCheck error disappeared after making sure the static route's outgoing interface always has an IP address. So, we should always add route after IP address, and remove the route before the IP address.
2. The second "missing interface" error is from arp_update. This disappeared after making sure there is an arp entry for …
=> Porting:17934-to-msft.202405: T2:Snappi Tests:Cisco-8000:Remove la_error ignore fixture, and fix the occurance of LA errors

ansible/generate_topo.py
Cherry-pick generate_topo.py changes in  https://github.com/sonic-net/sonic-mgmt/pull/18159 only  into 202412 to avoid conflict.  
Removed LT2 part of change as it's not needed in 202412.
> ### Description of PR
> Summary: Adding LT2 topology and support for generate_topo. We needed to modify the PortChannel name to only use `PortChannel10` for multi-asic only to avoid the interface name more than 15 characters which will violate linux interface name.
> 
> Fixes # (issue) 32099755
> 
> ### Type of change
> * [ ]  Bug fix
> * [ ]  Testbed and Framework(new/improvement)
> * [ ]  New Test case
>   
>   * [ ]  Skipped for non-supported platforms
> * [ ]  Test case improvement
> 
> ### Back port request
> * [ ]  202012
> * [ ]  202205
> * [ ]  202305
> * [ ]  202311
> * [ ]  202405
> * [ ] …
=> [202412][Partial PR: 18159] cherry-pick generate_topo change only in #18159

tests/lldp/test_lldp.py
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/15715
Otherwise we're failing at 
…(#15715)
The test test_lldp_neighbor_post_orchagent_reboot fails on multi-asic system. The test tries to disable autorestart feature for swss by using the namespace container name, e.g., swss0, swss1, etc
For config feature autorestart disable, it needs to use 'swss' as global feature name
Changed code to use 'swss' as feature name without using namespace id
run sonic-mgmt test_lldp.py
---------
Signed-off-by: Anand Mehra anamehra@cisco.com
=> [202503] Fixed swss feature name for test_lldp_neighbor_post_orchagent_reboot (#15715)

ansible/vars/topo_t1-isolated-d56u1-lag.yml, ansible/vars/topo_t1-isolated-d56u2.yml, ansible/vars/topo_t1-isolated-v6-d56u1-lag.yml, ansible/vars/topo_t1-isolated-v6-d56u2.yml
Summary:
As discussed, revert topo change in #18152 and use a different topo name for t1-isolated-lag topo which has upstream port-channel.
cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18683 into 202412
use new name for t1-isolated topo with upstream port-channel.
=> [202412][PR#18683] revert topo change in #18152 and add t1-isolated-lag topo

tests/common/helpers/constants.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/everflow/everflow_test_utilities.py, tests/everflow/test_everflow_ipv6.py, tests/everflow/test_everflow_testbed.py
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18622
=> [202503] Enhance everflow test on LT2/FT2 topology (#18622)

tests/common/cisco_data.py, tests/qos/qos_sai_base.py, tests/snappi_tests/cisco/helper.py, tests/snappi_tests/files/helper.py, tests/snappi_tests/pfc/test_global_pause_with_snappi.py, tests/snappi_tests/pfc/test_lossless_response_to_external_pause_storms.py, tests/snappi_tests/pfc/test_lossless_response_to_throttling_pause_storms.py, tests/snappi_tests/pfc/test_m2o_fluctuating_lossless.py, tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless.py, tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless_lossy.py, tests/snappi_tests/pfc/test_m2o_oversubscribe_lossy.py, tests/snappi_tests/pfc/test_pfc_mixed_speed.py, tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py, tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py, tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py, tests/snappi_tests/pfc/test_pfc_pause_response_with_snappi.py, tests/snappi_tests/pfc/test_pfc_pause_unset_bit_enable_vector.py, tests/snappi_tests/pfc/test_pfc_pause_zero_mac.py, tests/snappi_tests/pfc/test_pfc_port_congestion.py, tests/snappi_tests/pfc/test_tx_drop_counter_with_snappi.py, tests/snappi_tests/pfc/test_valid_pfc_frame_with_snappi.py, tests/snappi_tests/pfc/test_valid_src_mac_pfc_frame.py
Summary:
Recently cisco-8000 enabled VoQ Watchdog feature, which is similar to PfcWd feature. It drops the packets which get stuck in voq, and resets all the counters, when the interface is experiencing congestion due to pfc Xoff. This causes a number of failures in the PFC scripts which assume there is no watchdog. To prevent these failures, we add a fixture to disable the voq Watchdog in all DUT asics, and enable it at the end of the script.
This PR uses the voq-wd-disable function implemented in https://github.com/sonic-net/sonic-mgmt/pull/17937
Pls see description.
Implemented a new fixture to disable voq Watchdog.
Ran the failing test:
```
====================================================================================================================== warnings summary …
```
=> Porting 18564 to msft.202405: T2:snappi_tests:Add a fixture to disable voq watchdog, use it in pfc scripts.

tests/test_pretest.py
This reverts commit 7551587556a45487974c1af5d665de9892adadeb.
I thought we cherry picked the multithreading run of pretest PR (https://github.com/sonic-net/sonic-mgmt/pull/17493) into msft.202405 but we never did, so the PR https://github.com/sonic-net/sonic-mgmt/pull/18699 should never be cherry picked into msft.202405 as it's only a fix when test_pretest.py runs with multithreading.
In msft.202405 branch, we are running test_pretest.py (e.g. test_disable_startup_tsa_tsb_service()) in a normal for loop: https://github.com/Azure/sonic-mgmt.msft/blob/202405/tests/test_pretest.py#L385, so we should use duthost instead of dut
=> Revert "[action] [PR:18699] fix: correct DUT variable name in startup tsa pretest (#344)"

tests/conftest.py, tests/macsec/test_docker_restart.py
Cheery-picking PR#https://github.com/sonic-net/sonic-mgmt/pull/18518 and PR#https://github.com/sonic-net/sonic-mgmt/pull/18725 for  msft-202405 branch
cherry-pick 2 PRs in 1, as 18725 covers regression from 18518
Summary:
=> [Cherry-pick][macsec]Update test_docker_restart to use macsec host only

tests/common/snappi_tests/snappi_fixtures.py, tests/common/snappi_tests/traffic_generation.py, tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py, tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py, tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_burst_storm_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py, tests/snappi_tests/pfcwd/test_pfcwd_actions.py, tests/snappi_tests/qos/files/packet_reorder_helper.py, tests/snappi_tests/test_multidut_snappi.py, tests/snappi_tests/test_snappi.py
Summary:
Recently we introduced a function to use static-route and static-routed destinations for traffic in snappi scripts. This was needed for cisco-8000 to make sure that the split-voq functionality is used, and in addition, the connected route was not the use case scenario as well.
In this PR, we propagate the changes to newly rewritten/merged multidut code, which now can be run on T0/T1 and T2. So with this change all scripts use static route for cisco-8000.
Cisco-8000 uses split voq only when the packets are destined to routed dests. The snappi scripts were written for connected routes, which is not the usecase for cisco-8000 platform. This PR changes the traffic to static-routed destinations.
Changed all ipv4.dst.values to the new function that will return static routed dest for …
=> Porting 18388 to 202405.: Snappi: T0/T1/T2: Convert all traffic to static routed destinations in snappi scripts

ansible/group_vars/sonic/variables, ansible/module_utils/port_utils.py
**Description of PR**
Summary: Add new Arista SKUs to sonic-mgmt framework. This is a cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/18158
**Approach**
To add Arista-7280DR(A|AK|AM)-36S? to sonic-mgmt framework.
**How did you do it?**
Added the HwSKUs in the ansible directory
**How did you verify/test it?**
We are running sonic-mgmt tests internally
**Any platform specific information?**
Depends on https://github.com/sonic-net/sonic-buildimage/pull/22463
=> [Cherry-pick] Add Arista-7280DR(A|AK|AM)-36(|S) SKUs to sonic-mgmt

tests/snappi_tests/files/helper.py, tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py, tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py, tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py, tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py, tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
For Cisco 8000 derive the no of test streams to be created based on src and dest port on different ASIC or DUT and if the src port speed is > 200G
Description of PR
For IXIA snappi tests (originally tested for 400G ports speeds), we had multiple traffic streams:
backplane port is 200G, so we cannot push single stream of 400G
multiple streams gets load balanced across backplane ports
When going to 100G ports as source MSFT is asking to not use multiple streams.
Use multiple streams only for cisco-8000 and only if source port is 400G.
Any platform specific information?
Cisco8000 only
=> Multiple test streams for Cisco8000

ansible/roles/vm_set/library/vm_topology.py, ansible/roles/vm_set/tasks/add_topo.yml, ansible/roles/vm_set/tasks/remove_topo.yml, ansible/roles/vm_set/tasks/renumber_topo.yml
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18790
Summary:  This PR add option to use batch_mode support for bind_fp_ports. Which improves the speed by 50% tested on 128 VM neighbor.
Fixes # (issue) 32654908
When doing ovs flow creation, we're launching subprocess and waiting for each subprocess result before continue with the next call. This process is very inefficient even with the aid of multi-threading support.
This PR change the behavior of multi-threading in the following way:
1. Batching all the ovs flow creation commands that needed to execute into a single file
2. Launch 1 process to call `ovs-ofctl` on the file using add-flows, put the process into queue for wait later and free the thread so that the same thread can be use to launch a different batch
3. In the end, …
=> [202503] add batch_mode support for bind_fp_ports and unbind_fp_ports (#18790)

ansible/generate_topo.py, ansible/vars/topo_ft2-64.yml, ansible/vars/topo_lt2-p32o64.yml
Cherry-pick https://github.com/sonic-net/sonic-mgmt/pull/18915
Summary: Correct the ASN number of LT2 and FT2
Fixes # (issue) 33226573
- Correct the ASN number of FT2 to LT2. For these 2 groups we should have the same ASN.
- Added some missing code for generate_topo
=> [202503] chore: adjust ASN value for LT2 and FT2 (#18915)

tests/common/helpers/ntp_helper.py
NTP Service name differs based on type. Classic NTP has service name of `ntp` while NTPSEC on Bookworm has service name as `ntpsec`. This PR sets the service name based on type.
Bring in changes from -
- https://github.com/sonic-net/sonic-mgmt/pull/18627
- https://github.com/sonic-net/sonic-mgmt/pull/18583
=> Set NTP service name by type

tests/common/helpers/platform_api/sfp.py, tests/platform_tests/api/test_sfp.py
The changes to the sonic-mgmt testcases are required due to the below changes:
https://github.com/sonic-net/sonic-platform-common/pull/556
https://github.com/sonic-net/sonic-platform-daemons/pull/604
https://github.com/sonic-net/sonic-utilities/pull/3844
This PR also reverts the changes made by #181 .
=> [202503] Fix txvr tests after diagnostic table restructuring

ansible/roles/vm_set/tasks/main.yml
Support deploy thousands of ceos/net containers on a single server.
Set kernel.pty.max to 8192 in add-topo ansible-playbook.
Verified by deploy physical testbed.
=> [add-topo] Set kernel.pty.max to 8192 (#19054)

tests/dash/gnmi_utils.py, tests/gnmi/helper.py
Sync PR #16179 from sonic-net/sonic-mgmt to 202412.
Original PR: https://github.com/sonic-net/sonic-mgmt/pull/16179
=> [202412][PR:16179] Update gnmi test to support python3 gnmi client

ansible/library/test_facts.py, tests/common/testbed.py
In PRs: https://github.com/sonic-net/sonic-mgmt/pull/15643 and https://github.com/sonic-net/sonic-mgmt/pull/15881
We implemented multi-servers testbed design, however, to enable parsing multi-servers testbed definition, raise this PR to fix out of key error.
The code is already in master branch, and we only need the four lines code to be backport to 202411 and 202405
=> Skip multiple servers testbed parsing on branch 202405

ansible/roles/eos/tasks/ceos.yml, ansible/roles/eos/templates/dpu-tor.j2, ansible/roles/eos/templates/m0-mx.j2, ansible/roles/eos/templates/t0-8-lag-leaf.j2, ansible/roles/eos/templates/t0-backend-leaf.j2, ansible/roles/eos/templates/t0-leaf-lag-2.j2, ansible/roles/eos/templates/t0-leaf.j2, ansible/roles/eos/templates/t0-mclag-leaf.j2, ansible/roles/eos/templates/t0-v6-leaf.j2, ansible/roles/eos/templates/t1-28-lag-spine.j2, ansible/roles/eos/templates/t1-28-lag-tor.j2, ansible/roles/eos/templates/t1-56-lag-tor.j2, ansible/roles/eos/templates/t1-64-lag-tor.j2, ansible/roles/eos/templates/t1-8-lag-spine.j2, ansible/roles/eos/templates/t1-8-lag-tor.j2, ansible/roles/eos/templates/t1-backend-tor.j2, ansible/roles/eos/templates/t1-lag-spine.j2, ansible/roles/eos/templates/t1-lag-tor.j2, ansible/roles/eos/templates/t2-core.j2, ansible/roles/eos/templates/t2-leaf.j2, ansible/roles/eos/templates/t2-vs-core.j2, ansible/roles/eos/templates/t2-vs-leaf.j2
The upgraded cEOS instance also changes from single-agent to multi-agent mode.  This includes a behaviour change around the next-hop-self feature.
Fixes: BUG872880
Fixing a bug introduced by using a newer version of cEOS for testing. While the current documentation doesn't specify a newer version of cEOS, it would be good to have this fix in place before people start using a newer version of cEOS.
Adjust the cEOS configuration templates to force cEOS to rewrite the next-hop as itself
Normal sonic-mgmt test run
Any platform specific information?
Not platform-dependent.
Supported testbed topology if it's a new test case? All
=> [cherry-pick] Update cEOS configuration to use next-hop-self (#18659)

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
multiple hash/test_generic_hash.py::test_ecmp_and_lag_hash[CRC_CCITT-IN_PORT: is defined in the mark condition. keep only one.
bug fixing
=> Fix mark_conditions for test_ecmp_and_lag_hash

tests/common/helpers/ptf_tests_helper.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/common/utilities.py, tests/generic_config_updater/test_packet_trimming_config.py, tests/packet_trimming/conftest.py, tests/packet_trimming/constants.py, tests/packet_trimming/packet_trimming_helper.py, tests/packet_trimming/test_packet_trimming.py
Cherry-pick packet trimming test case to 202412 branch. The original PR is https://github.com/sonic-net/sonic-mgmt/pull/18051
=> [202412] Add packet trimming test cases (#18051)

ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/conftest.py, tests/generic_config_updater/test_portchannel_interface.py, tests/l2/test_l2_configure.py, tests/pfcwd/conftest.py, tests/qos/test_tunnel_qos_remap.py
Code sync sonic-net/sonic-mgmt:202411 => 202412
```
*   3124d5243 (HEAD -> code-sync-202412, origin/code-sync-202412) r12f 250710:1626 - Merge remote-tracking branch 'base/202411' into code-sync-202412
|\
| * b1b95dc51 (base/202411) zitingguo-ms 250513:1848 - Fix PortChannel name matching in verify_attr_change to handle leading spaces (#18301)
| * 7461bf3fd wrideout-arista 250604:1542 - Determine if the eos switch is running in multiagent mode, and stop/start the (#18748)
| * 4346afda4 Dashuai Zhang 250411:0103 - update d18u8s4 PT0 ASN to 4 bytes (#17888)
| * de1b1b4ac Ryangwaite 250709:1028 - Skip multi-hop upgrade tests on non-T0 testbeds (#19078) (#19326)
| * 573d42da8 Cong Hou 250709:0232 - Update the skip for test test_qos_dscp_mapping.py (#19381)
| * 3eb65b934 Yawen 250708:1743 - …
```
=> [202412] Code sync sonic-net/sonic-mgmt:202411 => 202412

tests/acl/test_acl.py
Remove broken PT0 condition for t1-isolated-d32/128 acl port selection that is not applicable for the topo.
This fixes the tests in test_acl.py for t1-isolated-d32/128
Only affecting 202412 as regression occurred after merging 202411 changes:
https://github.com/Azure/sonic-mgmt.msft/commit/fb533969e599bb32cf3a95803b9a4d64071daddc
=> Fix test_acl for t1-isolated-d32/128 due to PT0 condition

tests/common/platform/interface_utils.py, tests/common/platform/transceiver_utils.py, tests/common/plugins/conditional_mark/tests_mark_conditions.yaml, tests/platform_tests/test_xcvr_info_in_db.py
Cherry pick https://github.com/sonic-net/sonic-mgmt/pull/19170 to 202412.
* Added a helper function to get the first subport of logical ports to check for DOM values.
* Get first subport for all logical ports.
* Check the DOM for only first subports.
* Optimize the sonic db query.
* Skip the pc/test_retry_count.py::test_retry_count test to pass the CI since the test is always failing and has nothing to do with the current change.
=> [202412] Check DOM for only first subport for test_xcvr_info_in_db.py test.

ansible/library/show_ipv6_interface.py, tests/common/devices/sonic_asic.py, tests/common/plugins/sanity_check/checks.py, tests/common/utilities.py
Enable pretest with ipv6 testbeds [#19584](https://github.com/sonic-net/sonic-mgmt/pull/19584)
Cherry-pick from https://github.com/sonic-net/sonic-mgmt/pull/19584
=> Enable pretest with ipv6 testbeds (#19584)

tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
skipped generic_config_updater.test_pfcwd_status and generic_config_updater/test_pfcwd_interval for non-supported hwsku SN5640 and Arista7060X6PE. Resolve 202412 conflicts in https://github.com/sonic-net/sonic-mgmt/pull/19751 
Add non-supported hwsku to conditional markers
Veried it in sonic mgmt test generic_config_updater.test_pfcwd_status and generic_config_updater/test_pfcwd_interval:
```
========================================================================================== short test summary info =========================================================================================== SKIPPED [1] generic_config_updater/test_pfcwd_interval.py:143: This test can only support mellanox platforms …
```
=> [test_pfcwd_status][test_pfcwd_interval] fix syntax to skip pfcwd related tests for hwsku SN5640 and Arista7060X6PE (#19751)
